import { StepContent, StepSection, Paragraph, Callout, DecisionChallenge } from '@/components/lesson/StepComponents';
import { ticketBookingChallenges } from '../challenges';

export function AdmissionStep() {
 return (<StepContent>
<Callout label="The decision">{"The database is healthy at a controlled rate and collapses when everyone retries. A waiting room must protect useful work, not simply move an unbounded queue into application memory."}</Callout>
<StepSection title="Control attempts, not just arrivals"><Paragraph>{"Assume an event-shard load test sustains 600 hold attempts/s with realistic seat skew, synchronous durability, and payment/release work. At a 60% operating target, 360 attempts/s is a database ceiling, not an inventory admission target. Start the illustrative funnel at 80 attempts/s while inventory permits: 50% hold success gives H = 40/s; 50% checkout conversion gives P = 20/s after the checkout delay. These assumed ratios must be measured and change near sellout. Against 8,333 arrivals/s and one attempt each, 8,253/s wait or are rejected at that operating point. Throttle repeated attempts per session as well."}</Paragraph></StepSection>
<StepSection title="Tokens and fairness"><Paragraph>{"Use signed, short-lived permits bound to event, principal, purchase intent, and nonce. The admission service owns a replicated queue/permit store with atomic nonce-to-operation claims. Repeating the same claim recovers its decision; using it for another operation is rejected. If replay state is lost or cannot be read, fail closed and rotate the permit epoch before reopening."}</Paragraph><Paragraph>{"A 60-second permit at 80 grants/s needs at most 4,800 live nonce records/event; even the 360/s ceiling needs 21,600. At an illustrative 100 bytes/record this is 0.48 MB or 2.16 MB logical, before indexes, replicas, and safety retention."}</Paragraph><Paragraph>{"This is grant volume, not 8,333 arrivals/s: queue enrollment must separately handle that arrival rate. A capped 100,000-entry queue at 200 bytes/entry is 20 MB logical. Publish a pre-sale lottery/FIFO policy and rejoin behavior; accounts are not proof of unique humans."}</Paragraph></StepSection>
<StepSection title="Capacity feedback and outages"><Paragraph>{"Set admission to the minimum allowed by the tested attempt ceiling, in-flight/lock budget, available inventory, and payment backlog headroom. Use authoritative aggregate counts fed from committed changes and conservatively reserve headroom for telemetry lag and outstanding permits. When available seats approach zero, pause grants and coalesce inventory refreshes instead of deliberately feeding conflicts into row locks. A cached count may underutilize seats; it cannot authorize ownership. Rising conflict fraction, expiry lag, or unresolved payment age reduces the gate even with healthy DB latency. Reserve capacity for status, expiry, callbacks, and reconciliation; pause new holds if admission state is unavailable."}</Paragraph></StepSection>
<StepSection title="Queue arithmetic has limits"><Paragraph>{"At 80 grants/s, a bounded queue of 100,000 users with one attempt each and no new arrivals takes at least 100,000 ÷ 80 = 1,250 seconds to offer each an attempt, only if that rate can continue. The 360/s database ceiling would yield 278 seconds, but is not this funnel’s operating rate. Neither is a ticket ETA: this event has at most 25,000 two-seat sales and no-sale quarantine recycling can fall to about 21 groups/s. Pause/reduce grants as inventory is tied up and stop purchase ETAs at sellout."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"Admission spends scarce downstream capacity deliberately. A fast rejection is preferable to a timeout that invites duplicate work."}</Callout>
<DecisionChallenge challenge={ticketBookingChallenges["overload"]!} />
<StepSection title="Defend the design"><Paragraph>{"The payment provider slows down while hold latency is fine. Which signal should close the gate?"}</Paragraph></StepSection>
</StepContent>);
}
