import { StepContent, StepSection, Paragraph, Callout, CodeBlock } from '@/components/lesson/StepComponents';

export function ApiDataStep() {
 return (<StepContent>
<Callout label="The decision">{"A mobile client sends a hold request, loses the response, and retries through another server. A random request ID per retry creates a second operation; a stable operation ID lets us discover the first."}</Callout>
<StepSection title="API contract"><Paragraph>{"POST /events/{event}/holds carries a server-issued purchase_intent_id, seat IDs, quote version, and an Idempotency-Key. Authenticate the principal and enforce purchase limits in the same authority boundary as holds. Return 201 only after commit, 409 for unavailable seats or conflicting payload, 410 OPERATION_EXPIRED for an expired retry identity, and 429 for admission limits. Authenticated GET /events/{event}/purchase-intents/{id} resolves the hold, booking, or terminal result even after the HTTP replay window. Booking status reads authoritative state after mutations. A timeout means unknown, not rejected."}</Paragraph></StepSection>
<StepSection title="Keys and ownership"><Paragraph>{"Inventory uses (event_id, seat_id) as its primary key, with state, hold_id, and generation. Holds contain principal_id, expiry, seat list, and quote. A server-issued purchase intent is a durable business identity bound to the principal and event, with one immutable canonical hold payload and at most one hold. Unique (event_id, principal_id, operation, key) binds transport retries to a request hash and result. Unique (event_id, purchase_intent_id) on holds prevents a fresh HTTP key from repeating the same purchase intent. Bookings are unique per hold and contain a stable payment operation ID. Keep these records on the event shard."}</Paragraph></StepSection>
<StepSection title="Bounded replay and privacy"><Paragraph>{"The illustrative 24-hour window limits cached HTTP response replay, not business deduplication. Issue signed operation tokens with server timestamps; clients cannot refresh an old identity by editing its timestamp."}</Paragraph><Paragraph>{"After expiry return 410 OPERATION_EXPIRED, perform no mutation, and include the authorized intent/status URL. Retain the compact intent-to-result mapping or a terminal tombstone through the event and reconciliation lifecycle; after archival or deletion, unknown/retired server-issued intents fail closed rather than being recreated."}</Paragraph><Paragraph>{"Do not auto-mint a new purchase intent on timeout or expiry. Recover the existing result first; a deliberately separate purchase requires explicit user action and purchase-limit checks. Idempotency cannot infer that two different business intents mean the same human purchase. Provider retention is a separate contract. Check ownership on every read and keep personal/payment data out of snapshots and logs."}</Paragraph></StepSection>
<CodeBlock code={"inventory PRIMARY KEY (event_id, seat_id)\nhold PRIMARY KEY (event_id, hold_id)\nhold UNIQUE (event_id, purchase_intent_id)\nbooking UNIQUE (event_id, hold_id)\nrequest UNIQUE (event_id, principal_id, operation, key)\noutbox UNIQUE (event_id, operation_id)\ninbox UNIQUE (provider, provider_event_id)"} language="text" />
<Callout label="Our choice and its cost">{"The request key identifies an operation, the hold ID identifies a reservation, and the payment operation ID identifies one financial attempt. Reusing one indiscriminately hides bugs."}</Callout>
<StepSection title="Defend the design"><Paragraph>{"What happens if the same key arrives concurrently with two different seat lists?"}</Paragraph></StepSection>
</StepContent>);
}
