import { StepContent, StepSection, Paragraph, Callout } from '@/components/lesson/StepComponents';

export function AvailabilityStep() {
 return (<StepContent>
<Callout label="The decision">{"A green seat turns unavailable after a click. That can be an honest product experience. Showing a purchased seat as reserved for two people cannot."}</Callout>
<StepSection title="Separate static geometry from changing state"><Paragraph>{"Cache venue geometry, seat-index mapping, price/quote data, and public descriptions separately at versioned CDN URLs. Dynamic full-event snapshots encode AVAILABLE, HELD, PAYMENT_PENDING, and SOLD with two bits per seat plus geometry version, commit watermark, and generated-at time. For 50,000 seats this is 12.5 KB raw status, budgeted as 20 KB on the wire with metadata/encoding. Do not ship the internal 200-byte-per-seat objects (10 MB/event) at each poll. Geometry/price downloads and protocol overhead need separate egress budgets. Private booking/status responses use no-store and require authorization."}</Paragraph></StepSection>
<StepSection title="Budget the read path"><Paragraph>{"From the launch envelope, 200,000 map requests/s × 20 KB = 4 GB/s to viewers. An illustrative 99% CDN hit ratio leaves 2,000 origin requests/s; this is a target to test, not a guaranteed cache property. A server-side snapshot cache can reduce database reads further. Cold starts and many distinct event keys can invalidate that assumption."}</Paragraph></StepSection>
<StepSection title="Invalidation still races"><Paragraph>{"An inventory-owned projector bootstraps a consistent database snapshot at a commit watermark, then consumes committed changes from a resumable change stream. Apply changes in source order, deduplicate replay, and atomically publish only a newer complete watermark plus geometry version; rebuild from a consistent snapshot if history has been truncated. The diagram collapses this worker into the projection edge. Coalesce rebuilds rather than querying 50,000 rows per viewer."}</Paragraph><Paragraph>{"Illustrative healthy budget: ≤2 seconds projection lag, ≤2 seconds total shared-cache age, and ≤5 seconds until browser refresh gives about 9 seconds of visible lag plus transport time. These are monitored targets, not a hard bound during failure. Use no-cache in browsers and shared-cache revalidation so cache ages do not silently stack. Display the source timestamp and mark over-budget maps stale; CDN invalidation cannot purge an already rendered browser view. Every hold still checks authoritative inventory."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"We trade map freshness for read capacity while keeping ownership decisions authoritative. Origin analytics miss browser-cache hits unless separate client telemetry is collected."}</Callout>
<StepSection title="Defend the design"><Paragraph>{"Would you pay for per-seat WebSocket updates? Estimate recipient fan-out before replacing polling."}</Paragraph></StepSection>
</StepContent>);
}
