import { StepContent, StepSection, Paragraph, Callout, CodeBlock } from '@/components/lesson/StepComponents';

export function BaselineStep() {
 return (<StepContent>
<Callout label="The decision">{"Begin with a booking application and one transactional database. More services do not improve the proof that two buyers cannot own the same seat."}</Callout>
<StepSection title="The atomic boundary"><Paragraph>{"For a new hold, validate a distinct, bounded seat list. Begin a transaction, claim the retry key, and lock the purchase intent. Return its existing hold/result for an identical payload, even with a fresh HTTP key; reject changed payloads. Otherwise lock the requested inventory rows in ascending seat ID order. Confirm every row exists and is AVAILABLE; otherwise roll back the whole group. Insert the unique hold for that intent, mark every seat HELD with its hold ID and generation, and save the response before committing."}</Paragraph></StepSection>
<StepSection title="Keep the critical section short"><Paragraph>{"Never wait for the user or a payment network inside the transaction. The five-minute hold is a persisted business lease; the row lock lasts only for the transaction. A crashed process releases its transaction locks while committed business holds survive. Use bounded lock waits and retry deadlocks with the same operation identity."}</Paragraph></StepSection>
<StepSection title="Acknowledgement boundary"><Paragraph>{"Atomicity means a transaction commits the whole seat group or none; it does not by itself guarantee that an acknowledged commit survives failover. Our survival promise assumes synchronous durable AZ copies, acknowledgement only after the configured durable commit boundary, and promotion only of a fenced, sufficiently caught-up authority. An async replica can lose an acknowledged whole hold, enabling resale after unsafe promotion even though the original transaction was atomic. The regional-failure page makes that trade-off explicit. In this baseline, replicas and ingress are collapsed, not unnecessary. Later diagrams also collapse the snapshot projector into the versioned projection edge; recovery workers run expiry scans."}</Paragraph></StepSection>
<CodeBlock code={"BEGIN;\n-- Claim request key; lock intent; return existing result.\nSELECT * FROM inventory\n WHERE event_id = :event AND seat_id = ANY(:seats)\n ORDER BY seat_id FOR UPDATE;\n-- Assert exact row count and all AVAILABLE.\n-- Insert hold; update ALL rows; persist response.\nCOMMIT; -- only now acknowledge"} language="text" />
<Callout label="Our choice and its cost">{"The database owns inventory. Every release, reservation, and sale must pass through its transaction rules. Restrict direct table writes to trusted application procedures."}</Callout>
<StepSection title="Defend the design"><Paragraph>{"What if the third of four requested seats is already held? Show the rollback and the retry result."}</Paragraph></StepSection>
<Paragraph>Source: <a href="https://www.postgresql.org/docs/current/explicit-locking.html" target="_blank" rel="noreferrer">PostgreSQL row locks and deadlocks</a>. The scenario and architecture are illustrative.</Paragraph>
</StepContent>);
}
