import { StepContent, StepSection, Paragraph, Callout } from '@/components/lesson/StepComponents';

export function OperationsStep() {
 return (<StepContent>
<Callout label="The decision">{"The payment provider recovers after ten minutes. All workers retry together, overwhelm it again, and keep inventory quarantined. Recovery is its own workload."}</Callout>
<StepSection title="Backlog arithmetic"><Paragraph>{"Use the earlier per-event funnel: 80 attempts/s × 50% hold success × 50% checkout conversion = 20 payment intents/s after pipeline delay. Starting with no payment backlog, 600 seconds of provider outage would add 12,000 unresolved intents and reserve 24,000 seats if admission stays open. This fits a 50,000-seat event only if existing sold/HELD/pending occupancy leaves that headroom; it is not a reason to keep admitting."}</Paragraph><Paragraph>{"With non-converters holding 300 seconds, their steady occupancy alone is 20 × 300 × 2 = 12,000 seats, plus up to 20 × 300 × 2 = 12,000 seats in converting holds before checkout. In that worst hold-time example, 24,000 + 12,000 + 12,000 = 48,000 reserved seats leaves only 2,000 free, assuming no prior sales or pending work. Admission must drop before headroom disappears; the 20/s rate cannot continue through a full 900-second outage at those residence times."}</Paragraph></StepSection>
<StepSection title="Drain rate is net completed work"><Paragraph>{"Suppose the provider and local ledger can together complete 100 reconciliations/s. With only 2,000 seats of headroom in the worst hold-time example, pause new holds and first-time checkout during initial drain; keep status, callbacks, and recovery available, and let existing hold clocks continue. New intent arrival is then zero: net drain = 100 − 0 = 100/s, so 12,000 ÷ 100 = 120 seconds. Even an intent created at outage start and resolved last would be 600 + 120 = 720 seconds old, leaving 180 seconds before its 900-second deadline in this idealized model. Prioritize oldest deadlines. Confirmation turns reserved seats into sold seats; it does not free capacity. Reopen from actual availability, not falling payment queue depth. In general, drain time = backlog ÷ (completed service rate − new arrival rate); if service ≤ arrivals, there is no drain. Include retries, closures, refunds, and pre-existing backlog; service means completed operations, not HTTP attempts. Across events sum their actual rates under the shared provider limit."}</Paragraph></StepSection>
<StepSection title="Measure invariants and customer harm"><Paragraph>{"Track overlapping seat ownership, confirmed bookings without matching successful payment, aged unknown charges, refund age, issuance lag, and expiry lag. Separate sold-out conflicts from infrastructure errors. Watch per-event lock waits and aborts, oldest outbox/inbox age, webhook rejection rate, and admission fairness cohorts. Trace operation IDs across services without logging payment credentials."}</Paragraph></StepSection>
<StepSection title="Recovery must not poll the database to death"><Paragraph>{"Index pending outbox work by (state, next_attempt_at, operation_id). Claim small due batches with SKIP LOCKED and short leases; release transactions before network calls. Use exponential backoff with jitter, a maximum polling interval, a provider circuit breaker, and per-shard concurrency/query budgets. Empty scans back off too. Persist next_attempt_at; a crashed lease is reclaimable with the same operation identity. Give expiry, inbox application, and financial reconciliation reserved capacity separate from new payment dispatch. Inventory on-call owns expiry lag; payment on-call owns unresolved charges and refund age. Outage recovery must respect these budgets and the remaining deadline, escalating rather than silently discarding obligations."}</Paragraph></StepSection>
<StepSection title="Storage and lifecycle"><Paragraph>{"Illustrative volume: 100 events/day × 25,000 orders = 2.5M orders/day. At 2 KB/order, that is 5 GB/day logical. A 90-day hot tier is 450 GB; a one-year archive is 1.825 TB before indexes, replicas, audit events, backups, and hold attempts. With a 1.5× row/index allowance and three copies, hot capacity is 2.025 TB. Retention requires business and jurisdiction review, not an arbitrary forever policy."}</Paragraph></StepSection>
<StepSection title="Exercise the crash windows"><Paragraph>{"Inject failure after hold commit before response, after provider success before save, after inbox commit before processing, and during expiry/checkout races. Test duplicate and reordered callbacks, stale epochs, clock shifts, cache cold starts, and sold-out retry storms. Roll out state changes compatibly: old workers must understand or safely reject new states; drain work without losing durable obligations."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"Use bounded concurrency, exponential backoff with jitter, per-provider budgets, and explicit manual escalation. Never discard financial recovery obligations just to make queue depth fall."}</Callout>
<StepSection title="Defend the design"><Paragraph>{"Which alarms page immediately, and which indicate an acceptable degraded seat map?"}</Paragraph></StepSection>
</StepContent>);
}
