import { StepContent, StepSection, Paragraph, Callout, CodeBlock, DecisionChallenge } from '@/components/lesson/StepComponents';
import { ticketBookingChallenges } from '../challenges';

export function PaymentsStep() {
 return (<StepContent>
<Callout label="The decision">{"The provider cannot join your inventory transaction. A charge can succeed while your database is unavailable. Treat that gap as a normal state, not an exceptional log line."}</Callout>
<StepSection title="Durable intent before the network"><Paragraph>{"Checkout locks the hold first and looks up its existing booking before evaluating the original hold expiry. An identical checkout returns that booking and status URL (202 while pending, 200 with a terminal result), even with a fresh HTTP key; it never creates another charge. Reject conflicting checkout parameters with 409."}</Paragraph><Paragraph>{"For a first checkout, lock seats in sorted order, check ownership, quote, and sampled database time, then atomically create PAYMENT_PENDING, payment_started_at, recovery_deadline = payment_started_at + 900 seconds, and one payment outbox operation. UNIQUE(event_id, hold_id) is the final guard: after a uniqueness race rolls back, re-read and return the authorized existing booking. Keep seats reserved. A worker calls the provider outside the transaction using the stored stable operation key; closure may race an in-flight call, requiring compensation."}</Paragraph></StepSection>
<StepSection title="Confirm only verified success"><Paragraph>{"For this immediate-charge flow, apply outcomes under the common hold → sorted seats → booking lock order. Only PAYMENT_PENDING may become CONFIRMED with seats SOLD and an issuance outbox event, and only if database time sampled under the lock is before recovery_deadline. Verify provider object, merchant account, amount, currency, and booking metadata; a client redirect is not evidence. Only PAYMENT_PENDING may become FAILED and release seats on a verified terminal failure. Duplicate events are no-ops; stale failure events never release CONFIRMED seats. Ambiguous provider ordering requires querying current state, not last-arrival-wins."}</Paragraph></StepSection>
<StepSection title="Close uncertainty explicitly"><Paragraph>{"At or after recovery_deadline, an unresolved PAYMENT_PENDING booking is eligible for an atomic CLOSED transition and seat release, retaining a reconciliation obligation. If success processing first acquires the lock after that deadline, it closes and creates a refund obligation instead of confirming. CLOSED never becomes CONFIRMED. A late failure needs no refund. Confirmation and closure use the same lock order and state guards; only one wins. The 900 seconds start at checkout, in addition to time already spent HELD. Release may happen later if workers or the authority are unavailable; the regional-freeze page defines recovery without pausing the clock."}</Paragraph></StepSection>
<StepSection title="Compensation has a customer cost"><Paragraph>{"A customer can temporarily have a charge but no ticket. Show pending/refund status and escalation ownership. If that experience is unacceptable, choose authorization-before-capture with a separate capture-recovery design; do not pretend authorizations never expire or that capture is infallible."}</Paragraph></StepSection>
<CodeBlock code={"HELD -> PAYMENT_PENDING -> CONFIRMED (SOLD)\nHELD -> EXPIRED (AVAILABLE)\nPAYMENT_PENDING -> FAILED (AVAILABLE)\nPAYMENT_PENDING -> CLOSED (AVAILABLE)\nCLOSED + late success -> REFUND_PENDING -> REFUNDED\n-- CLOSED never transitions to CONFIRMED"} language="text" />
<Callout label="Our choice and its cost">{"We choose bounded inventory quarantine followed by durable refund compensation. This guarantees seat exclusivity under our storage assumptions, not an atomic transaction with the payment provider."}</Callout>
<DecisionChallenge challenge={ticketBookingChallenges["late-payment"]!} />
<StepSection title="Defend the design"><Paragraph>{"A success callback races the closure job. List the two legal outcomes and the financial obligation in each."}</Paragraph></StepSection>
</StepContent>);
}
