import { StepContent, StepSection, Paragraph, Callout } from '@/components/lesson/StepComponents';

export function RecapStep() {
 return (<StepContent>
<Callout label="The decision">{"A staff engineer asks you to erase every box and rebuild from the guarantees. Start with the two buyers competing for the last two seats, then explain each boundary you add."}</Callout>
<StepSection title="Reconstruct the system"><Paragraph>{"A public map suggests seats. Admission grants permission to attempt. The event writer atomically holds the group and records retry identity. Checkout persists payment intent while retaining inventory. Workers and verified callbacks converge financial state. Confirmation atomically sells seats and schedules issuance; closure instead releases them and retains compensation obligations."}</Paragraph></StepSection>
<StepSection title="Name every authority"><Paragraph>{"Inventory transactions decide ownership. Database time under the hold lock decides checkout and payment-deadline eligibility. Durable purchase intent and booking identity survive HTTP key expiry. The provider determines payment outcome; the booking ledger decides whether it can still confirm or must refund. The directory owns routing epochs, storage/cluster fencing owns write authority, and admission owns permit replay state. Cached maps, browser timers, and callback arrival order decide none of these. Each unavailable authority has an explicit pause or recovery policy."}</Paragraph></StepSection>
<StepSection title="Adversarial review"><Paragraph>{"Derive 83/s versus 21/s recycling and explain why neither is the 360/s attempt ceiling. Reproduce the 20 intents/s funnel and 12,000-operation outage backlog while accounting for held and sold seats. Explain the 20 KB wire map versus 10 MB internal projection. Recover a purchase after its HTTP key expires without creating a new intent. Prove that duplicate checkout, stale expiry, reordered failure callbacks, and freeze recovery cannot resell a confirmed seat. Defend the hot-event partition and name who restores sweeper liveness."}</Paragraph></StepSection>
<StepSection title="What to validate before production"><Paragraph>{"Benchmark realistic seat skew and lock queues, test the chosen provider’s deduplication and refund behavior, verify durability and fencing with fault injection, and rehearse restore and reconciliation. Our numbers are illustrative inputs. These pages teach a design and its proof obligations, not a running ticket service or a measured capacity claim."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"An excellent answer is not the longest component list. It is a defensible chain from product promise to state transition, failure behavior, recovery, and cost."}</Callout>
<StepSection title="Defend the design"><Paragraph>{"Change one assumption: payment resolution can take two days. Would you hold the seat, delay payment initiation, or accept a refund-based outcome? Defend the customer experience."}</Paragraph></StepSection>
</StepContent>);
}
