import { StepContent, StepSection, Paragraph, Callout, DecisionChallenge } from '@/components/lesson/StepComponents';
import { ticketBookingChallenges } from '../challenges';

export function RegionalFailureStep() {
 return (<StepContent>
<Callout label="The decision">{"Region A acknowledged the last two seats and then disappeared. Region B is behind. Promoting B immediately may make those same seats available again."}</Callout>
<StepSection title="State the failure model"><Paragraph>{"Use one writable authority per event and synchronously durable copies across selected availability zones. Acknowledge only at the configured durability boundary. Fencing must prevent an isolated old primary from accepting writes after promotion. Synchronous replication trades latency and availability for a stronger acknowledged-write guarantee within those failure assumptions."}</Paragraph></StepSection>
<StepSection title="Regional history can be uncertain"><Paragraph>{"An asynchronous remote replica may lack acknowledged holds or sales. RPO is how much data can be lost; RTO is time to restore service. Neither is made zero by drawing a replica. We choose to freeze mutations for affected events until the committed history and ownership can be established. Keep browsing clearly stale and show payment/booking status as temporarily unavailable when it cannot be proven."}</Paragraph></StepSection>
<StepSection title="A safe failover runbook"><Paragraph>{"Stop admission, fence the old writer through storage/cluster authority, verify the candidate’s committed position, restore authoritative history if needed, promote and update the event directory, reconcile payment operations, then reopen gradually. If history cannot be recovered, quarantine affected inventory and use financial/issuance records plus human remediation; do not claim automatic zero-loss recovery."}</Paragraph></StepSection>
<StepSection title="If the business requires continued selling"><Paragraph>{"Evaluate a cross-region consensus-backed store with its quorum and latency trade-offs, or preallocate disjoint inventory ownership to regions. Disjoint quotas reduce utilization and make group seating harder. Neither option permits two regions to own the same assigned seat during a partition."}</Paragraph></StepSection>
<StepSection title="Deadlines keep running while writes are frozen"><Paragraph>{"Persist absolute recovery deadlines; the clock does not pause. While authoritative history is uncertain, neither confirmation nor closure may mutate inventory, so physical quarantine can exceed 15 minutes."}</Paragraph><Paragraph>{"After fencing and restoring history, keep admission and new charge dispatch paused. Resume bounded inbox/status reconciliation and deadline processing under the normal locks: before-deadline verified success may confirm; overdue pending bookings close, and any success creates a refund obligation, even if the provider charged before the deadline. Already CONFIRMED history stays confirmed. Rate-limit closures, releases, and refunds instead of launching a mass sweep, then reopen admission gradually from actual released inventory. A delayed callback may cost a customer their seats; do not quietly promise deadline extensions."}</Paragraph></StepSection>
<StepSection title="Durability must fit the latency target"><Paragraph>{"The 500 ms hold-decision p99 includes synchronous replica acknowledgement and failover-safe commit, not just SQL execution. Benchmark the configured topology with skew and replica stalls; do not add component p99 values and call the sum an end-to-end p99. If required replicas cannot acknowledge, wait only within a bounded request deadline and report unknown when commit outcome is uncertain. Keep the durability policy rather than silently switching to async to meet latency; reduce admission or accept unavailability. Status lookup resolves the same operation once authority returns."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"For this design, unavailable is preferable to selling an already acknowledged seat again. This can consume the earlier availability error budget."}</Callout>
<DecisionChallenge challenge={ticketBookingChallenges["regional-safety"]!} />
<StepSection title="Defend the design"><Paragraph>{"Can a payment record reconstruct an uncharged but acknowledged hold? What does that imply for recovery?"}</Paragraph></StepSection>
<Paragraph>Source: <a href="https://www.postgresql.org/docs/current/warm-standby.html" target="_blank" rel="noreferrer">PostgreSQL synchronous and asynchronous standby trade-offs</a>. The scenario and architecture are illustrative.</Paragraph>
</StepContent>);
}
