import { StepContent, StepSection, Paragraph, Callout } from '@/components/lesson/StepComponents';

export function RequirementsStep() {
 return (<StepContent>
<Callout label="The decision">{"It is 09:59. A concert has 50,000 assigned seats. One million fans are about to arrive. Two people select the same pair. Which response are you willing to make irreversible?"}</Callout>
<StepSection title="Define the promises"><Paragraph>{"Within one event, a seat has at most one live owner. A group of up to four seats is held all-or-nothing. Confirmation requires both durable seat ownership and verified successful payment. A seat map may be stale; a successful hold may not be imaginary. A queue position is permission to try, not a promise of inventory."}</Paragraph></StepSection>
<StepSection title="Illustrative launch envelope"><Paragraph>{"Assume 1,000,000 visitors arrive over 600 seconds: 1,667 arrivals/s on average. A 5× burst is 8,333 arrivals/s. If all remain and refresh every 5 seconds, that is 200,000 map requests/s. Budget 20 KB per compact full-event status snapshot: 50,000 seats × 2 bits = 12,500 bytes, leaving 7,500 bytes for version, timestamp, encoding, and metadata. Seat indices reference separately cached venue geometry; prices, seat labels, and buyer data are not repeated. At 20 KB/response, payload is 4 GB/s before protocol overhead. These are decimal units and illustrative assumptions, not observed traffic."}</Paragraph></StepSection>
<StepSection title="Inventory bounds the funnel"><Paragraph>{"Assume a 2-seat average group: 50,000 ÷ 2 = at most 25,000 sold groups without cancellations. Distinguish admitted attempts A, successful holds H, and payment intents P: P ≤ H ≤ A for the same cohort, although checkout occurs later."}</Paragraph><Paragraph>{"If no buyers check out and each hold expires after 300 seconds, ideal saturated recycling is 25,000 ÷ 300 ≈ 83 groups/s. If every hold enters payment just before expiry and stays unresolved for another 900 seconds, it is 25,000 ÷ (300 + 900) ≈ 21 groups/s. These are different no-sale recycling scenarios; sweeper delay lowers both. Neither is sustainable sales throughput: confirmed sales permanently consume this finite inventory."}</Paragraph></StepSection>
<StepSection title="Size occupancy before setting admission"><Paragraph>{"For a no-sale steady state, H × E[time in HELD] + P × E[time in PAYMENT_PENDING] ≤ unsold seats ÷ 2. Use measured residence times and the actual seat-count distribution; the two-seat model is an approximation. During launch or an outage, track current HELD, pending, sold, and available seat counts instead of assuming steady state. Later pages use an illustrative 80 attempts/s, 50% hold success, and 50% checkout conversion: H = 40/s and P = 20/s after the checkout delay. These are planning inputs while inventory remains, not promises to keep the gate open."}</Paragraph></StepSection>
<StepSection title="Capacity and service objectives"><Paragraph>{"For 100 active events, 50,000 seats/event × 200 bytes/internal projected seat = 1 GB logical working set before allocator overhead and replicas (10 MB/event). This richer in-memory projection is not the wire snapshot; 100 compact 20 KB snapshots occupy 2 MB before cache overhead."}</Paragraph><Paragraph>{"Proposed targets: hold-decision p99 under 500 ms after admission; 99.9% monthly mutation availability, or 30 × 24 × 60 × 0.001 = 43.2 minutes of error budget. Include lock waits, commit, and synchronous AZ replication in the measured end-to-end latency. Correctness takes priority during uncertain ownership."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"We start with assigned seating, one event per order, fixed quoted prices, and a five-minute hold. Resale, cross-event atomic baskets, and offline venue admission are separate products."}</Callout>
<StepSection title="Defend the design"><Paragraph>{"If marketing demands “everyone gets a fair chance,” does that mean FIFO arrival, a pre-sale lottery, or equal purchase limits?"}</Paragraph></StepSection>
</StepContent>);
}
