import { StepContent, StepSection, Paragraph, Callout, DecisionChallenge } from '@/components/lesson/StepComponents';
import { ticketBookingChallenges } from '../challenges';

export function SeatContentionStep() {
 return (<StepContent>
<Callout label="The decision">{"Ten thousand buyers want row A. Adding ten thousand application threads makes the database queue longer; it does not create ten thousand copies of row A."}</Callout>
<StepSection title="Two valid mechanisms"><Paragraph>{"Pessimistic row locks serialize contenders before checking state. Optimistic conditional updates compare state or version and require exactly the expected row count, rolling back the entire group on any mismatch. Both can enforce exclusivity in the authoritative database. Optimistic retries are attractive at low collision rates; concentrated conflict makes wasted work significant."}</Paragraph></StepSection>
<StepSection title="A concrete interleaving"><Paragraph>{"Buyer A locks seats 11 and 12. Buyer B waits for seat 11. A commits HELD. B acquires the lock, sees HELD, and returns conflict rather than applying its earlier seat-map read. If A aborts instead, B can acquire both. A fixed lock order reduces deadlocks; bounded waits and whole-transaction retry still matter."}</Paragraph></StepSection>
<StepSection title="Why an external lease is insufficient"><Paragraph>{"If a Redis lease expires while an old worker pauses, a new worker can acquire it and both can later write. A lease can reduce load, but storage must enforce ownership/version checks. Adding a lock service adds another failure boundary without removing database arbitration. For this scenario, start with row locks; bound contention before it reaches the database."}</Paragraph></StepSection>
<StepSection title="Where the queue is actually bounded"><Paragraph>{"Enforce an event-wide in-flight limit at admission, split into bounded per-instance budgets, and use a bounded application queue/connection pool. PostgreSQL does not expose a per-seat maximum waiter count. SET LOCAL lock_timeout limits each lock acquisition wait; statement_timeout and an application request deadline bound the wider attempt. For example, a 50 ms lock timeout is a tuning input, not a measured latency guarantee or a total transaction limit. On lock timeout, abort the transaction and return a retryable busy response with backoff; do not report sold out or spin-retry. A lost commit response still requires status lookup. Load-test these limits with synchronous replication inside the 500 ms hold-decision target."}</Paragraph></StepSection>
<Callout label="Our choice and its cost">{"One seat is inherently serialized. Scale independent seats and events, reject stale attempts quickly, and avoid retries that amplify the hot row."}</Callout>
<DecisionChallenge challenge={ticketBookingChallenges["seat-race"]!} />
<StepSection title="Defend the design"><Paragraph>{"When would optimistic updates be cheaper than locking, and which measurements would change your choice?"}</Paragraph></StepSection>
<Paragraph>Source: <a href="https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-LOCK-TIMEOUT" target="_blank" rel="noreferrer">PostgreSQL lock and statement timeouts</a>. Application admission supplies the count bound; a timeout supplies a wait bound.</Paragraph>
</StepContent>);
}
