import type { LessonDefinition } from '@/types/lesson';

export const urlShortenerLesson: LessonDefinition = {
  archetypeId: 'url-shortener',
  title: 'URL Shortener',
  contentVersion: 1,
  steps: [
    {
      id: 'requirements',
      title: 'Requirements & Scale',
      shortTitle: 'Requirements',
      objective: 'Define the functional and non-functional requirements for a URL shortening service, and establish scale assumptions.',
      diagramStateId: 'empty',
      concepts: [],
    },
    {
      id: 'api-data',
      title: 'API & Data Model',
      shortTitle: 'API & Data',
      objective: 'Design the REST API endpoints and database schema for creating and resolving short URLs.',
      diagramStateId: 'empty',
      concepts: ['database-index'],
    },
    {
      id: 'baseline',
      title: 'Baseline Architecture',
      shortTitle: 'Baseline',
      objective: 'Build the simplest architecture that fulfills the requirements: client, application server, and database.',
      diagramStateId: 'baseline',
      highlightedNodes: ['client', 'app-server', 'database'],
      flowSequenceId: 'create-flow',
      concepts: [],
    },
    {
      id: 'id-generation',
      title: 'Short-Code Generation',
      shortTitle: 'ID Generation',
      objective: 'Explore strategies for generating unique short codes: random generation with collision handling versus sequential ID encoding.',
      diagramStateId: 'baseline',
      concepts: ['idempotency'],
    },
    {
      id: 'cache',
      title: 'Caching Layer',
      shortTitle: 'Caching',
      objective: 'Add a cache to reduce database load for popular redirects, using cache-aside pattern with TTL-based expiration.',
      diagramStateId: 'with-cache',
      highlightedNodes: ['cache-node'],
      flowSequenceId: 'cache-hit-flow',
      concepts: ['cache'],
    },
    {
      id: 'scaling',
      title: 'Scaling the Service',
      shortTitle: 'Scaling',
      objective: 'Scale horizontally with stateless replicas, load balancing, read replicas, and consider when partitioning is warranted.',
      diagramStateId: 'scaled',
      highlightedNodes: ['load-balancer-node'],
      concepts: ['load-balancer'],
    },
    {
      id: 'reliability',
      title: 'Reliability & Failure Modes',
      shortTitle: 'Reliability',
      objective: 'Analyze what happens when components fail and design graceful degradation strategies.',
      diagramStateId: 'scaled',
      concepts: ['cache', 'load-balancer'],
    },
    {
      id: 'tradeoffs',
      title: 'Design Trade-offs',
      shortTitle: 'Trade-offs',
      objective: 'Evaluate key design decisions: redirect status codes, mutable links, abuse prevention, and analytics.',
      diagramStateId: 'scaled',
      concepts: [],
    },
    {
      id: 'recap',
      title: 'Recap & Interview Prep',
      shortTitle: 'Recap',
      objective: 'Review the complete architecture, summarize design rationale, and practice with interview-style follow-up questions.',
      diagramStateId: 'scaled',
      concepts: [],
    },
  ],
};
