import type { ArchetypeMetadata } from '@/types/archetype';
import { urlShortenerMetadata } from './url-shortener/metadata';

export const archetypeCatalog: readonly ArchetypeMetadata[] = [
  // Foundation & Core Applications
  urlShortenerMetadata,
  {
    id: 'product-catalog',
    title: 'Product Catalog',
    description: 'Design a read-heavy product catalog with search, filtering, and content management. Focus on scaling reads, CDN caching, and data denormalization.',
    stage: 'foundation',
    sequence: 2,
    availability: 'planned',
    tags: ['read-scaling', 'cdn', 'search', 'denormalization'],
  },
  {
    id: 'photo-video',
    title: 'Photo Sharing & Video Delivery',
    description: 'Design media upload, processing, storage, and delivery pipelines. Covers blob storage, CDN distribution, transcoding, and thumbnail generation.',
    stage: 'foundation',
    sequence: 3,
    availability: 'planned',
    tags: ['media', 'blob-storage', 'cdn', 'transcoding', 'upload'],
  },
  {
    id: 'notifications',
    title: 'Notification Service',
    description: 'Design a multi-channel notification system supporting push, email, and SMS. Covers background processing, queues, rate limiting, and delivery tracking.',
    stage: 'foundation',
    sequence: 4,
    availability: 'planned',
    tags: ['background-processing', 'queues', 'rate-limiting', 'delivery'],
  },
  {
    id: 'home-timeline',
    title: 'Home Timeline',
    description: 'Design a social media home feed with fan-out strategies, ranking, and real-time updates. Covers push vs. pull models and hybrid approaches.',
    stage: 'foundation',
    sequence: 5,
    availability: 'planned',
    tags: ['fan-out', 'feeds', 'ranking', 'social', 'real-time'],
  },
  {
    id: 'product-search',
    title: 'Product Search & Autocomplete',
    description: 'Design search with indexing, ranking, autocomplete, and spell correction. Covers inverted indexes, Elasticsearch, and relevance tuning.',
    stage: 'foundation',
    sequence: 6,
    availability: 'planned',
    tags: ['search', 'elasticsearch', 'autocomplete', 'indexing'],
  },
  {
    id: 'chat',
    title: 'Real-Time Chat',
    description: 'Design a messaging system with WebSocket connections, presence, delivery receipts, and message persistence. Covers connection management and ordering.',
    stage: 'foundation',
    sequence: 7,
    availability: 'planned',
    tags: ['websocket', 'messaging', 'real-time', 'presence'],
  },
  {
    id: 'ticket-booking',
    title: 'Ticket Booking',
    description: 'Design a reservation system handling concurrent bookings, inventory management, and seat selection. Covers distributed locking and consistency.',
    stage: 'foundation',
    sequence: 8,
    availability: 'planned',
    tags: ['reservations', 'inventory', 'locking', 'consistency'],
  },
  {
    id: 'checkout',
    title: 'Checkout & Payments',
    description: 'Design a checkout flow with payment processing, order management, and transaction workflows. Covers sagas, idempotency, and failure recovery.',
    stage: 'foundation',
    sequence: 9,
    availability: 'planned',
    tags: ['payments', 'sagas', 'idempotency', 'transactions', 'workflows'],
  },
  // Advanced Distributed Systems
  {
    id: 'event-streams',
    title: 'Event Streams & Analytics',
    description: 'Design event ingestion, stream processing, and analytics pipelines. Covers Kafka, windowed aggregations, and exactly-once semantics.',
    stage: 'advanced',
    sequence: 10,
    availability: 'planned',
    tags: ['kafka', 'streaming', 'analytics', 'event-driven'],
  },
  {
    id: 'location-matching',
    title: 'Location & Matching',
    description: 'Design a ride-matching or delivery system with geospatial indexing, real-time location tracking, and efficient matching algorithms.',
    stage: 'advanced',
    sequence: 11,
    availability: 'planned',
    tags: ['geospatial', 'matching', 'real-time', 'location'],
  },
  {
    id: 'distributed-infra',
    title: 'Distributed Infrastructure',
    description: 'Explore distributed consensus, service discovery, configuration management, and multi-region deployment patterns.',
    stage: 'advanced',
    sequence: 12,
    availability: 'planned',
    tags: ['consensus', 'service-discovery', 'multi-region', 'infrastructure'],
  },
  {
    id: 'collaborative-editing',
    title: 'Collaborative Editing',
    description: 'Design a real-time collaborative editor using CRDTs or operational transformation. Covers conflict resolution, cursor presence, and offline support.',
    stage: 'advanced',
    sequence: 13,
    availability: 'planned',
    tags: ['crdt', 'collaboration', 'real-time', 'conflict-resolution'],
  },
  // GenAI Systems
  {
    id: 'llm-request-response',
    title: 'LLM Request/Response Apps',
    description: 'Design applications built on large language models with prompt management, response streaming, and cost optimization.',
    stage: 'genai',
    sequence: 14,
    availability: 'planned',
    tags: ['llm', 'prompts', 'streaming', 'ai'],
  },
  {
    id: 'conversational-assistants',
    title: 'Conversational Assistants',
    description: 'Design multi-turn conversational AI systems with context management, memory, and personality. Covers session handling and safety guardrails.',
    stage: 'genai',
    sequence: 15,
    availability: 'planned',
    tags: ['chatbot', 'conversation', 'memory', 'ai'],
  },
  {
    id: 'rag',
    title: 'Retrieval-Augmented Generation',
    description: 'Design RAG systems with document ingestion, vector search, chunk management, and grounded generation. Covers embedding pipelines and reranking.',
    stage: 'genai',
    sequence: 16,
    availability: 'planned',
    tags: ['rag', 'vector-search', 'embeddings', 'retrieval'],
  },
  {
    id: 'tool-agents',
    title: 'Tool-Using Agents & Workflows',
    description: 'Design AI agents that use tools, plan multi-step actions, and orchestrate complex workflows. Covers function calling, safety, and execution graphs.',
    stage: 'genai',
    sequence: 17,
    availability: 'planned',
    tags: ['agents', 'tool-use', 'orchestration', 'function-calling'],
  },
  {
    id: 'multimodal-agents',
    title: 'Real-Time Multimodal Agents',
    description: 'Design agents processing text, audio, and video in real-time. Covers streaming pipelines, modality fusion, and latency optimization.',
    stage: 'genai',
    sequence: 18,
    availability: 'planned',
    tags: ['multimodal', 'real-time', 'audio', 'video', 'ai'],
  },
  {
    id: 'async-generation',
    title: 'Asynchronous Generation Pipelines',
    description: 'Design batch and asynchronous AI generation systems for images, documents, and content. Covers job queues, progress tracking, and output management.',
    stage: 'genai',
    sequence: 19,
    availability: 'planned',
    tags: ['generation', 'async', 'batch', 'content-pipeline'],
  },
  {
    id: 'model-serving',
    title: 'Model Serving & AI Gateways',
    description: 'Design infrastructure for serving ML models at scale with routing, caching, rate limiting, fallbacks, and multi-model management.',
    stage: 'genai',
    sequence: 20,
    availability: 'planned',
    tags: ['model-serving', 'gateway', 'ml-ops', 'infrastructure'],
  },
];

export const STAGE_LABELS: Record<string, string> = {
  foundation: 'Foundation & Core Applications',
  advanced: 'Advanced Distributed Systems',
  genai: 'GenAI Systems',
};

export const STAGE_ORDER: string[] = ['foundation', 'advanced', 'genai'];
