import type { FC } from 'react';
import type { StepComponentProps } from '@/types/lesson';
import { StepContent, StepSection, Paragraph, CodeBlock, DecisionChallenge } from '@/components/lesson/StepComponents';
import { urlShortenerChallenges } from '../challenges';
import { CacheLoadExplorer } from '../components/CacheLoadExplorer';

export const CacheStep: FC<StepComponentProps> = () => (
  <StepContent>
    <StepSection title="Cache the mapping, not the browser redirect">
      <Paragraph>{"At about 400 average reads/s, a cache is not justified by the 10:1 ratio alone. Benchmark the database with the real index and storage footprint. A 20,000/s burst, hot-key skew, and database headroom may justify Redis. Latency and cost depend on deployment; RAM does not guarantee a universal sub-millisecond p99."}</Paragraph>
      <Paragraph>{"Chosen HTTP policy: 302 + Cache-Control: no-store on every redirect. Redis is an internal server-side cache, so both hits and misses still reach the application for validity checks. A browser TTL would suppress those requests; a CDN redirect cache would need its own freshness and invalidation policy, which this design does not include."}</Paragraph>
    </StepSection>
    <StepSection title="Cache-aside with explicit validity">
      <Paragraph>Before the scaling step, the only database is the primary. The same cache-aside logic later uses a fresh replica lookup with primary fallback. The lookup adapter must establish freshness before returning a row; TTL alone cannot repair replica lag.</Paragraph>
      <Paragraph>{"The cache entry includes state, version, absolute expiry, and valid_until. Check validity on cache hits as well as misses. The illustrative internal freshness window is at most 30 seconds, jittered downward to 24–30 seconds and capped by link expiry. Unlike the HTTP response, an internal mapping is intentionally reusable."}</Paragraph>
      <CodeBlock language="typescript" code={"// Teaching pseudocode: adapters enforce deadlines and validation.\ninterface Mapping {\n  long_url: string;\n  state: 'ACTIVE' | 'DELETED' | 'BLOCKED';\n  version: number;\n  expires_at_ms: number | null;\n}\ninterface CachedMapping { row: Mapping; valid_until_ms: number }\n\nasync function resolve(code: string): Promise<CachedMapping | null> {\n  let entry: CachedMapping | null = null;\n  try {\n    entry = await cacheGet(code, { timeoutMs: 20 });\n  } catch { recordCacheError(); } // error != ordinary miss\n\n  const now = Date.now();\n  if (entry && now < entry.valid_until_ms) {\n    return usable(entry.row, now) ? entry : null;\n  }\n\n  // Baseline: primary read. Scaled: replay-checked replica, else primary.\n  // Per-instance singleflight + bounded fleet DB admission wrap this block.\n  const readStartedAt = Date.now();\n  const row = await freshMappingLookup(code, { timeoutMs: 200 });\n  if (!row || !usable(row, Date.now())) return null;\n\n  // Downward jitter preserves the maximum 30s freshness allowance.\n  const validUntil = Math.min(\n    readStartedAt + randomInteger(24_000, 30_000) - clockErrorAllowanceMs,\n    row.expires_at_ms ?? Infinity\n  );\n  if (Date.now() < validUntil) {\n    // Bounded fill queue; absolute expiry; reject older invalidated versions.\n    // Cache failure must not discard the authoritative result.\n    enqueueBoundedFill(code, { row, valid_until_ms: validUntil });\n  }\n  return { row, valid_until_ms: validUntil };\n}\nfunction usable(row: Mapping, now: number): boolean {\n  return row.state === 'ACTIVE' &&\n    (row.expires_at_ms === null || now < row.expires_at_ms);\n}\n\n// After resolve, on BOTH cache-hit and cache-miss paths:\n// Recheck valid_until, state, and expiry at the decision boundary.\n// If freshness elapsed, re-resolve within deadline or return 503.\n// Return 302 + Location + Cache-Control: no-store.\n// Total request deadline: 300ms; no independent unlimited retries."} />
      <Paragraph>{"The adapters above are teaching boundaries, not a runnable client library. Cache reads/writes need typed decoding, deadlines, and bounded queues. Use synchronized server clocks, subtract a measured clock-error allowance from the 30-second validity budget, and stop serving cached validity decisions if clock health cannot support the contract. Expiry is checked at decision time; a previously sent redirect cannot be recalled."}</Paragraph>
    </StepSection>
    <StepSection title="Edits, deletion, and stale refill races">
      <Paragraph>{"PATCH, DELETE, and abuse takedown atomically update state/version and append an invalidation outbox record. A retrying application relay deletes the cached value and advances a per-code version floor atomically in Redis. A fill must match or exceed that floor; while the floor is retained, a delayed pre-edit read cannot repopulate the old version after invalidation."}</Paragraph>
      <Paragraph>{"Retain version floors beyond the maximum old fill lifetime when possible, including request and queue deadlines. Eviction or a Redis restart can remove a floor, so version guards accelerate convergence but are not the hard freshness guarantee. Absolute validity is that boundary. Never extend a fill’s valid_until when a worker retries; use absolute expiration and discard expired fills. Even if invalidation is delayed or lost during cache recovery, freshness-checked values expire by their original 30-second validity limit. Do not restore old values with a fresh TTL. In-flight responses can finish within their request deadline after a change; instantaneous revocation would require a stronger per-request authority check and its availability cost."}</Paragraph>
      <Paragraph>{"Optional create warmup follows the same rule: capture its validity origin before the create transaction, cap it by expiry, and discard the fill if that deadline has passed. A delayed create response or retry must not give the original destination a fresh 30 seconds after a later edit. The simpler default is to let the first redirect populate the cache."}</Paragraph>
      <Paragraph>{"Tombstones keep deleted aliases reserved. Expiry does not depend on a cleanup sweep: every decision checks expires_at. Cleanup handles storage reclamation separately and must preserve alias-retention policy. We deliberately avoid negative caching initially, so a just-created code cannot be hidden by a cached 404."}</Paragraph>
    </StepSection>
    <StepSection title="Protect the database when Redis fails">
      <Paragraph>{"Singleflight collapses concurrent identical misses within one process. With N app instances, one cold-key wave can still cause up to N queries, and repeated waves or distinct keys add more. Bound per-instance queues and connection pools; assign fleet-wide database concurrency budgets and shed excess requests with retryable 503 rather than an unbounded fallback storm."}</Paragraph>
      <Paragraph>{"An optional distributed refresh lease can reduce duplicate fills while Redis is healthy. It cannot protect the database during Redis failure and is not inventory-style correctness authority. Jitter spreads independent expirations but does not remove a single hot-key stampede. Keep fill failures isolated from a successful database read."}</Paragraph>
    </StepSection>
<CacheLoadExplorer />
<DecisionChallenge challenge={urlShortenerChallenges['cache-eviction-ttl']!} />
<DecisionChallenge challenge={urlShortenerChallenges['thundering-herd-mitigation']!} />
<Paragraph>HTTP policy reference: <a href="https://www.rfc-editor.org/rfc/rfc9111.html#section-5.2.2.5" target="_blank" rel="noreferrer">RFC 9111: no-store</a>.</Paragraph>
  </StepContent>
);
